---
os: linux

dist: bionic

language: shell

git:
  submodules: true
  symlinks: true

branches:
  only:
  - master

cache:
  directories:
    - .test_files/

before_install:
  - ./tests/test_helper/travisci_before_install.sh

jobs:
  include:
  - name: libvirt_centos7
    env:
      - BOX_OS="centos7"
      - VAGRANT_DEFAULT_PROVIDER="libvirt"
  - name: virtualbox_centos7
    env:
      - BOX_OS="centos7"
      - VAGRANT_DEFAULT_PROVIDER="virtualbox"
  - name: libvirt_centos8
    env:
      - BOX_OS="centos8"
      - VAGRANT_DEFAULT_PROVIDER="libvirt"
  - name: virtualbox_centos8
    env:
      - BOX_OS="centos8"
      - VAGRANT_DEFAULT_PROVIDER="virtualbox"
  - name: libvirt_fedora
    env:
      - BOX_OS="fedora"
      - VAGRANT_DEFAULT_PROVIDER="libvirt"
  - name: virtualbox_fedora
    env:
      - BOX_OS="fedora"
      - VAGRANT_DEFAULT_PROVIDER="virtualbox"
  - name: libvirt_ubuntu
    env:
      - BOX_OS="ubuntu"
      - VAGRANT_DEFAULT_PROVIDER="libvirt"
  - name: virtualbox_ubuntu
    env:
      - BOX_OS="ubuntu"
      - VAGRANT_DEFAULT_PROVIDER="virtualbox"

script:
  - ./tests/test_helper/setup.sh
  - make versions
  - make test-bats
  - ls -ahl /var/run/libvirt /var/run/libvirt/libvirt-sock || true
